services:
  db:
    image: postgres:16-alpine
    container_name: finance_db
    environment:
      POSTGRES_USER: victor
      POSTGRES_PASSWORD: kingflammer
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - finance_db_data:/var/lib/postgresql/data

volumes:
  finance_db_data:
